# Generated by Django 6.1.1 on 2026-09-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
