# Generated by Django 6.1.1 on 2026-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_client_vente_lignevente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
